### ISSUE TITLE
Is jekyll the correct tool?

### ISSUE THREAD

**Issue by mariogrip** [Halium/docs#11]
Is jekyll the correct tool to use for docs pages? Would it not be better to use a tool made for docs like sphinx (and host it on https://readthedocs.org/) then we can make "easy to navigate" and nice looking docs like this http://docs.octoprint.org/

**Comment by bhush9** [comment]
Current version is quick "hack" I should say.. I am working on something like lineageos wiki.. which also uses the Jekyll, but if you think readthedocs is proper tool for it, we can setup that I guess

**Comment by bhush9** [comment]
I will look into setting up readthedocs.. and see how it goes

**Comment by bhush9** [comment]
Since we have moved to readthedocs, let's close this one...
