### ISSUE TITLE
PR Request: Add Supplementary Device: trlte Note 4

### ISSUE THREAD

**Issue by gripfastistech** [Halium/docs#161]
Please consider for Pull Request for Supplementary Device for the Samsung Galaxy Note 4 (trltexx).

[trltexx](https://github.com/gripfastistech/trltexx/blob/master/trltexx.rst)

https://github.com/gripfastistech/trltexx/blob/master/trltexx.rst

Please advise for revision/information/etc.

**Comment by doniks** [comment]
hi @gripfastistech thanks for your contributionn

pull requests roughly work like this:
* you fork Halium/docs on github 
* you clone your own fork onto your computer
* you create a branch for your trlte addition
* you put your information in there
* you commit those changes
* you push your branch from your computer back to github
* on github you create a Pull Request

does that make sense? can you do that? I'm sure there are plenty of guides online that explain this much nicer than I can

**Comment by gripfastistech** [comment]
@doniks ok lets make it official; will do, thanks

**Comment by gripfastistech** [comment]
@doniks pushed the trltexx branch PR

**Comment by gripfastistech** [comment]
@doniks OK, PR cli build pass what's next?

**Comment by JamiKettunen** [comment]
Since https://github.com/Halium/docs/pull/162 was merged long ago this should be closed
