### ISSUE TITLE
Add reference to my AutoFix-MKVC tool

### ISSUE THREAD

**Issue by scriptSQD** [Halium/docs#175]
@doniks Hi again, can you please explain me the way I can somehow mention the existence of my self-made tool: [AutoFix-MKVC](https://github.com/scriptSQD/autofix-mkcc)? You can read about it and its goals on the repo page. Sincerely waiting for your reply, scriptSQD.

**Comment by doniks** [comment]
Hi there! How about this: 1 present it in the halium telegram channel. It would be helpful to get some community feedback. 2. Simply make a PR where you mention it. Now depending on how 1 pans out, the PR could present it more or less prominently. Halium is pretty much a research and development project, so no problem to promote a new hobby project a'la "here's a thing you might find helpful for x". But if it is a smashing success in the community when you show them, it might right away be presented as The Way to do x. Makes sense?

**Comment by scriptSQD** [comment]
> Hi there! How about this: 1 present it in the halium telegram channel. It would be helpful to get some community feedback. 2. Simply make a PR where you mention it. Now depending on how 1 pans out, the PR could present it more or less prominently. Halium is pretty much a research and development project, so no problem to promote a new hobby project a'la "here's a thing you might find helpful for x". But if it is a smashing success in the community when you show them, it might right away be presented as The Way to do x. Makes sense?

Absolutely, will try it and determine what to do next!

**Comment by scriptSQD** [comment]
> Hi there! How about this: 1 present it in the halium telegram channel. It would be helpful to get some community feedback. 2. Simply make a PR where you mention it. Now depending on how 1 pans out, the PR could present it more or less prominently. Halium is pretty much a research and development project, so no problem to promote a new hobby project a'la "here's a thing you might find helpful for x". But if it is a smashing success in the community when you show them, it might right away be presented as The Way to do x. Makes sense?

By the way, can you supply me with the link, please?

**Comment by doniks** [comment]
https://docs.halium.org/en/latest/porting/first-steps.html#getting-help
