### ISSUE TITLE
[Fix]Possible telnet interface issue

### ISSUE THREAD

**Issue by DeadSquirrel01** [Halium/docs#18]
Hey, I have a samsung device....
I built hybris-boot, but i stucked at samsung logo screen, so I tried to use telnet debugging in init script.
After a week of trying, I found that the issue was the mac address.
This issue happens when the output of $ ip addr is something like:

6: enp0s29u1u3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff

(I pasted only my rndis interface)
As you can see, there is "link/ether 00:00:00:00:00:00" in the second line. (the "brd ff:ff:ff:ff:ff:ff" is useless for us). This means that there is no MAC address assigned to the interface, and if I try to bring it up with $ ip link set MyInterface up , I'll get:

RTNETLINK answers: Cannot assign requested address

To get rid of this error, you just have to assign a MAC address with:

$ ip link set interface address 02:01:02:03:04:08

Change "interface" with your RNDIS interface name.
Also 02:01:02:03:04:08 is just an example. You can set whetever MAC you want, it just need to be a "valid" mac. Otherwise the one in the example will work, so, there's no need to change it.

After assigned the MAC address you can bring the interface up with:

ip link set interface up

Still change "interface" with your RNDIS interface name

**Comment by doniks** [comment]
I have a Nexus 7 deb and in my dmesg I see:

```
[   16.684204] android_work: android_work: sent uevent USB_STATE=DISCONNECTED
[   16.775787] rndis_function_bind_config: rndis_function_bind_config MAC: 00:00:00:00:00:00
[   16.776000] android_usb gadget: using random self ethernet address
[   16.776092] android_usb gadget: using random host ethernet address
[   16.777557] usb0: MAC 26:0a:89:4e:69:25
[   16.777648] usb0: HOST MAC 5e:95:9c:10:4d:53
...
[   17.086730] msm_otg msm_otg: Avail curr from USB = 0
[   17.086914] android_work: android_work: did not send uevent (0 0   (null))
[   17.188964] msm_ta_detect_work: USB exit ta detection - frindex
[   17.205413] android_work: android_work: sent uevent USB_STATE=CONNECTED
[   17.208648] msm_otg msm_otg: Failed notifying 1 charger type to PMIC
[   17.209197] android_work: android_work: sent uevent USB_STATE=DISCONNECTED
[   17.345428] android_work: android_work: sent uevent USB_STATE=CONNECTED
[   17.346527] android_usb gadget: high-speed config #1: android_usb
...
[   17.399200] android_work: android_work: sent uevent USB_STATE=CONFIGURED
```

so it seems my kernel is setting a random mac address and thus doesn't seem to have this problem. So, what I'm trying to say, this problem doesn't exist for everyone. 

In my humble opinion, we could simply add a: If you have THIS error, do THAT to fix the mac address and move on. Thoughts?

**Comment by DeadSquirrel01** [comment]
I know, in fact I've already seen some people in the irc channel with working telnet, and in fact I was the only who had this error. Anyway, I didn't say everyone will get this error, but

This issue happens when the output of $ ip addr is something like:

6: enp0s29u1u3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff

Probably the title is wrong, since this is not an issue but a fix ;)

**Comment by doniks** [comment]
Wasn't meant as critique. I just tried to explain my train of thought leading to the suggestion to include a respective tip in the porting guide. Maybe you just want to propose a merge request. I think Marius et. al are receptive ;)

**Comment by DeadSquirrel01** [comment]
no, z3ntu just wanted me to put this in issue. Personally i didn't want to put it here. Anyway, I'll change the title to a "less critical" one ^^

**Comment by DeadSquirrel01** [comment]
I can close this now

**Comment by bhush9** [comment]
Um, lets close this when PR is merged.

**Comment by DeadSquirrel01** [comment]
Ok

**Comment by z3ntu** [comment]
@DeadSquirrel01 I just told you to write it down so it doesn't get lost in the endless voids of the chat history :wink:

**Comment by DeadSquirrel01** [comment]
Yes, but after the pull requested is merged, it's useless to keep this opem, since it'll be included in docs

**Comment by z3ntu** [comment]
Yep.
