### ISSUE TITLE
Every Subpage inside folders shows "page does not exist" in ReadTheDocs Docu Version

### ISSUE THREAD

**Issue by demokrit011** [Halium/docs#24]
Hi, just realized that all pages inside /docs/supplementary and /docs/porting are displayed and linked correctly inside github but transition via sphinx to Read the docs seems to break these.

**Comment by Ryuno-Ki** [comment]
I have some issues using sphinx locally. It would be helpful to have a requirements.txt listing the dependencies with the exact versions used for building.

Aside from that, [Makefile](https://github.com/Halium/docs/blob/61e3e52728eae831796f2b8791759a7f0782c720/Makefile#L6) should use `SPHINXBUILD = python3 -msphinx` to avoid further issues.

**Comment by bhush9** [comment]
What issues you do have with sphinx? any error or logs?

**Comment by Ryuno-Ki** [comment]
A messed up local installation. Hence I would prefer to use a virtualenv. Therefore I need the exact version of sphinx (plus which Python version was used). I have to many Python projects on my drive …

**Comment by ShalokShalom** [comment]
Is there any news?

**Comment by demokrit011** [comment]
Well on my side only a work-around: the pages are actually accessible if you click on the "dead" links and change the suffix from _*.md_ to _*.html_ so for example [https://docs.halium.org/en/latest/supplementary/device_overview.md]([https://docs.halium.org/en/latest/supplementary/device_overview.md) is accessible as [https://docs.halium.org/en/latest/supplementary/device_overview.html](https://docs.halium.org/en/latest/supplementary/device_overview.html) . However this introduces new issues since github-markdown seems to be unsupported so the tables are broken...

**Comment by delijati** [comment]
See limitations for `markdown` https://blog.readthedocs.com/adding-markdown-support/. An easy fix is to set ever `*.md` link to `*.html` in the source. Or to convert it to `rst`.

**Comment by vanyasem** [comment]
+1 for migrating to rST. And that should be done quickly, before we grow up too huge to change something

**Comment by delijati** [comment]
Done see #33
