### ISSUE TITLE
internet access from rootfs via usb

### ISSUE THREAD

**Issue by doniks** [Halium/docs#25]
It would help me if someone could document how I can connect to the internet from the device. 

In the porting guide we have described how to setup **local** networking between your development machine and the device via usb. I can ping both ways but I can't figure out how to connect to the **internet**.

**Comment by vanyasem** [comment]
If you managed to ssh to your device (you were able to boot Halium), just make sure that `NetworkManager` is running, and then use `mntui` to connect to your Wi-Fi network

You can learn more at [Arch Wiki](https://wiki.archlinux.org/index.php/Wireless_network_configuration)

**Comment by bhush9** [comment]
@vanyasem I think what @doniks means here is configuring reverse tethering to provide internet over USB when WiFi is not working

**Comment by doniks** [comment]
@bhush9 correct, that is what I mean
@vanyasem a description for wifi is already included in the porting guide https://github.com/Halium/docs/blob/master/porting/wifi.rst but for this you need working wifi drivers. Reverse tethering would help porters that don't have working wifi drivers yet

**Comment by UniversalSuperBox** [comment]
Something like this? https://wiki.ubports.com/wiki/Internet-over-the-debugging-rndis-connection

**Comment by bhush9** [comment]
That sounds like it.

**Comment by doniks** [comment]
ah nice. thanks! I'll piece a PR together for it

**Comment by doniks** [comment]
Uh, no, I don't get it. Can someone explain those two steps?

* "Also note your PC's IP on the rndis network, `192.168.2.*`. " 
* "Finally, note the interface name for the rndis network. We'll call that `[pf]`." 

How do I do that? Can someone give an example?

**Comment by doniks** [comment]
https://github.com/Halium/docs/pull/40

**Comment by doniks** [comment]
merged
